# Copy to secret.yaml and fill in values. Do not commit secret.yaml to git.
apiVersion: v1
kind: Secret
metadata:
  name: wedwise-secrets
type: Opaque
stringData:
  session-secret: "CHANGE_ME_USE_A_RANDOM_32_BYTE_SECRET"
